### ISSUE TITLE
Soufxx

### ISSUE THREAD

**Issue by Eloutmanixx** [GitbookIO/gitbook#2330]
## Bug description

_Please describe._  
_If this affects the front-end, screenshots would be of great help._

## How to reproduce

1.
2.
3.

## Additional context

```[tasklist]
### Tasks
- [ ] https://github.com/GitbookIO/gitbook/issues/2324
- [ ] https://github.com/GitbookIO/gitbook/pull/2328
- [ ] https://github.com/GitbookIO/gitbook/issues/2326
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by Eloutmanixx** [comment]
Tanko

**Comment by Eloutmanixx** [comment]
Hello thanks

**Comment by Eloutmanixx** [comment]
Hello
